networks:
  olkkani_network:
    external: true
services:
  blue:
    container_name: lfr-backend
    image:  ${IMAGE_NAME:-ghcr.io/olkkani/lostark-for-rice:latest}
    environment:
      - DB_MONGO_URL=${DB_MONGO_URL}
      - DB_CONNECTION_URL=${DB_CONNECTION_URL}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - API_KEY=${API_KEY}
      - TZ=Asia/Seoul
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - "18082:8080"
    networks:
      - olkkani_network
    restart: always