spring:
  profiles:
    group:
      local:
        - common
        - db-jpa-common
        - server-local
        - db-local
        - db-mongo-embedded
      prod:
        - common
        - db-jpa-common
        - server-prod
        - db-prod
        - db-mongo-prod
--- # common
spring:
  config:
    activate:
      on-profile: common
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
#  resource:
#    static-locations: classpath:/static
lostark:
  api:
    key: ${API_KEY}
--- # local-server
spring:
  config:
    activate:
      on-profile: server-local
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
server:
  port: 8080
--- # prod-server
spring:
  config:
    activate:
      on-profile: server-prod
  lifecycle:
    timeout-per-shutdown-phase: 30s
server:
  shutdown: graceful
---
spring:
  config:
    activate:
      on-profile: db-jpa-common
  jpa:
    properties:
      hibernate: # jpaEntityManagerFactory 에서 수동으로 DataSource 생성하고 해당 값을 가져오기 때문에 key naming 이 다름
        physical_naming_strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        implicit_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
---
spring:
  config:
    activate:
      on-profile: db-mongo-embedded
  data:
    mongodb:
      auto-index-creation: true
      port: 0
de:
  flapdoodle:
    mongodb:
      embedded:
        version: 6.0.8
        tools-version: 100.7.4
--- # db-prod-mongodb
spring:
  config:
    activate:
      on-profile: db-mongo-prod
  data:
    mongodb:
      uri: ${DB_MONGO_URL}
      auto-index-creation: true
--- # db-prod
spring:
  config:
    activate:
      on-profile: db-prod
  datasource:
    url: ${DB_CONNECTION_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
decorator:
  datasource:
    p6spy:
      enable-logging: false
--- # db-local
spring:
  config:
    activate:
      on-profile: db-local
  datasource:
    url: jdbc:h2:mem:local;MODE=PostgreSQL
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  sql:
    init:
      mode: always