spring:
  profiles:
    group:
      local:
        - common
        - persistence-common
        - persistence-local
        - server-local
        - db-mongo-embedded
      prod:
        - common
        - persistence-common
        - persistence-prod
        - server-prod
        - db-mongo-prod
--- # common
spring:
  config:
    activate:
      on-profile: common
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
management:
  endpoints:
    web:
      exposure:
        include: health
        exclude: "*"
lostark:
  api:
    key: ${API_KEY:must_not_null_apikey}
webhook:
  url:
    discord: ${DISCORD_WEBHOOK_URL:must_not_null_url}
--- # local-server
spring:
  config:
    activate:
      on-profile: server-local
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
server:
  port: 8080
--- # prod-server
spring:
  config:
    activate:
      on-profile: server-prod
  lifecycle:
    timeout-per-shutdown-phase: 30s
server:
  shutdown: graceful
---
spring:
  config:
    activate:
      on-profile: persistence-common
  jpa:
    properties:
      hibernate: # jpaEntityManagerFactory 에서 수동으로 DataSource 생성하고 해당 값을 가져오기 때문에 key naming 이 다름
        physical_naming_strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        implicit_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
---
spring:
  config:
    activate:
      on-profile: db-mongo-embedded
  data:
    mongodb:
      auto-index-creation: true
      port: 0
de:
  flapdoodle:
    mongodb:
      embedded:
        version: 6.0.8
        tools-version: 100.7.4
--- # db-prod-mongodb
spring:
  config:
    activate:
      on-profile: db-mongo-prod
  data:
    mongodb:
      uri: ${DB_MONGO_URL}
      auto-index-creation: true

--- # persistence-local
spring:
  config:
    activate:
      on-profile: persistence-local
  jpa:
    generate-ddl: true
    hibernate:
          ddl-auto: create-drop
  #    generate-ddl: false
  flyway:
    enabled: true # 명시적 선언
    baseline-on-migrate: true # springboot 2 이상에서 안되는 문제가 있어. 명시적 선언
    locations: classpath:db/migration
    baseline-version: 1
  #    locations: classpath:db/migration,classpath:db/seed
  datasource:
    url: jdbc:h2:mem:local;MODE=PostgreSQL
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
--- # db-prod
spring:
  config:
    activate:
      on-profile: persistence-prod

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
  flyway:
    enabled: true # 명시적 선언
    baseline-on-migrate: true # springboot 2 이상에서 안되는 문제가 있어. 명시적 선언
    locations: classpath:db/migration
    baseline-version: 1
  datasource:
    url: ${DB_CONNECTION_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
decorator:
  datasource:
    p6spy:
      enable-logging: false