spring:
  profiles:
    group:
      local:
        - common
      prod:
        - common
--- # common
spring:
  config:
    activate:
      on-profile: common
  r2dbc:
    url: ${DB_CONNECTION_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    properties:
      spring:
        r2dbc:
          mapping:
            camel-case: true
lostark:
  api:
    key: ${LOSTARK.API.KEY}