spring:
  r2dbc:
    url: ${DB_CONNECTION_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    properties:
      spring:
        r2dbc:
          mapping:
            camel-case: true
  datasource:
    driver-class-name: org.postgresql.Driver

lostark:
  api:
    key: ${LOSTARK.API.KEY}