spring:
  profiles:
    group:
      local:
        - common
        - server-local
        - db-local
      prod:
        - common
        - server-prod
        - db-prod
--- # common
spring:
  config:
    activate:
      on-profile: common
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
#  resource:
#    static-locations: classpath:/static
lostark:
  api:
    key: ${API.KEY}
--- # local-server
spring:
  config:
    activate:
      on-profile: server-local
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
server:
  port: 8080
--- # prod-server
spring:
  config:
    activate:
      on-profile: server-prod
  lifecycle:
    timeout-per-shutdown-phase: 30s
server:
  shutdown: graceful
--- # db-h2
spring:
  config:
    activate:
      on-profile: db-h2
--- # db-prod
spring:
  config:
    activate:
      on-profile: db-prod
  datasource:
    url: ${DB_CONNECTION_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
--- # db-local
spring:
  config:
    activate:
      on-profile: db-local
  datasource:
    url: jdbc:h2:mem:local;MODE=PostgreSQL
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  sql:
    init:
      mode: always