spring:
  profiles:
    group:
      local:
        - common
        - server-local
        - db-local
        - db-prod
      prod:
        - common
        - server-prod
        - db-prod
--- # common
spring:
  config:
    activate:
      on-profile: common
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
#  resource:
#    static-locations: classpath:/static
lostark:
  api:
    key: ${API.KEY}
--- # local-server
spring:
  config:
    activate:
      on-profile: server-local
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  thymeleaf:
    cache: false
    check-template-location: true
server:
  port: 8080
  undertow:
    threads:
      io: 20
      worker: 400
--- # prod-server
spring:
  config:
    activate:
      on-profile: server-prod
--- # db-h2
spring:
  config:
    activate:
      on-profile: db-h2
--- # db-prod
spring:
  config:
    activate:
      on-profile: db-prod
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_CONNECTION_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
      ddl-auto: validate
--- # db-local
spring:
  config:
    activate:
      on-profile: db-local
  datasource:
    p6spy:
      # JDBC 이벤트 로깅을 위한 P6LogFactory 등록
      enable-logging: true

      # com.p6spy.engine.spy.appender.MultiLineFormat 사용 (SingleLineFormat 대신)
      multiline: true

      # 기본 리스너들을 위한 로깅 사용 [slf4j, sysout, file, custom]
      logging: slf4j

      # 실제 값으로 '?'를 대체한 효과적인 SQL 문자열을 추적 시스템에 보고
      # 참고: 이 설정은 로깅 메시지에 영향을 주지 않음
      tracing:
        include-parameter-values: true